version: '3.8'

services:
  # Aplikasi Go Kita
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - APP_URL=http://localhost:8080
    depends_on:
      - redis
    
  # Database Redis (Super Cepat)
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"